name: root
description: Bussiness logic for the mobile app
homepage:

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  built_value: ^8.4.1
  built_collection: ^5.1.1
  freezed_annotation: ^2.1.0
  redux: ^5.0.0
  redux_epics: ^0.15.1
  flutter_redux: ^0.10.0
  firebase_core: ^1.4.0
  firebase_analytics: ^8.2.0
  firebase_crashlytics: ^2.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  built_value_generator: ^8.4.1
  freezed: ^2.1.0
  build_runner: ^2.2.0
flutter:
